name: PR Integration
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - uses: actions/cache@v4
        with:
          path: .next/cache
          key: nextjs-build-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nextjs-build-${{ runner.os }}-

      - name: Lint check
        run: npm run check

#TODO: implement tests
#      - name: Test
#        run: npm run test

      - name: Build
        run: npm run build
